### ISSUE TITLE
我在导入项目运行会NoClassDefFoundError错误，不知道原因。。。求作者帮忙指点下

### ISSUE THREAD

**Issue by justin-mc-lai** [wyhnihaook/Healer_Weather#1]
03-22 11:46:58.761 20127-20127/com.sjxz.moji_weather E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.sjxz.moji_weather, PID: 20127
                                                                       java.lang.NoClassDefFoundError: com.sjxz.moji_weather.fragment.WeatherFragment
                                                                           at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
                                                                           at java.lang.Class.getDexCacheType(Class.java:479)
                                                                           at java.lang.reflect.ArtMethod.getDexCacheType(ArtMethod.java:229)
                                                                           at java.lang.reflect.ArtMethod.getReturnType(ArtMethod.java:178)
                                                                           at java.lang.reflect.Method.getReturnType(Method.java:184)
                                                                           at java.lang.Class.getDeclaredMethods(Class.java:771)
                                                                           at de.greenrobot.event.SubscriberMethodFinder.findSubscriberMethodsWithReflection(SubscriberMethodFinder.java:127)
                                                                           at de.greenrobot.event.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:79)
                                                                           at de.greenrobot.event.EventBus.register(EventBus.java:135)
                                                                           at com.sjxz.moji_weather.base.BaseAppCompatActivity.onCreate(BaseAppCompatActivity.java:68)
                                                                           at com.sjxz.moji_weather.base.BaseActivity.onCreate(BaseActivity.java:42)
                                                                           at android.app.Activity.performCreate(Activity.java:5975)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522)
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:169)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                           at android.os.Looper.loop(Looper.java:194)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
                                                                        Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sjxz.moji_weather.fragment.WeatherFragment" on path: DexPathList[[zip file "/data/app/com.sjxz.moji_weather-2/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                           at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
                                                                           at java.lang.Class.getDexCacheType(Class.java:479) 
                                                                           at java.lang.reflect.ArtMethod.getDexCacheType(ArtMethod.java:229) 
                                                                           at java.lang.reflect.ArtMethod.getReturnType(ArtMethod.java:178) 
                                                                           at java.lang.reflect.Method.getReturnType(Method.java:184) 
                                                                           at java.lang.Class.getDeclaredMethods(Class.java:771) 
                                                                           at de.greenrobot.event.SubscriberMethodFinder.findSubscriberMethodsWithReflection(SubscriberMethodFinder.java:127) 
                                                                           at de.greenrobot.event.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:79) 
                                                                           at de.greenrobot.event.EventBus.register(EventBus.java:135) 
                                                                           at com.sjxz.moji_weather.base.BaseAppCompatActivity.onCreate(BaseAppCompatActivity.java:68) 
                                                                           at com.sjxz.moji_weather.base.BaseActivity.onCreate(BaseActivity.java:42) 
                                                                           at android.app.Activity.performCreate(Activity.java:5975) 
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111) 
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522) 
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:169) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                           at android.os.Looper.loop(Looper.java:194) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5546) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762) 
                                                                       	Suppressed: java.lang.NoClassDefFoundError: com.sjxz.moji_weather.fragment.WeatherFragment
                                                                           at dalvik.system.DexFile.defineClassNative(Native Method)
                                                                           at dalvik.system.DexFile.defineClass(DexFile.java:226)
                                                                           at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
                                                                           at dalvik.system.DexPathList.findClass(DexPathList.java:321)
                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
                                                                           		... 26 more
                                                                       	Suppressed: java.lang.ClassNotFoundException: com.sjxz.moji_weather.fragment.WeatherFragment
                                                                           at java.lang.Class.classForName(Native Method)
                                                                           at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                           at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                           		... 25 more
                                                                        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by wyhnihaook** [comment]
已修正，谢谢您的支持，欢迎再次下载
